/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.8.5
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = ESIClient.Dotcore.Client.SwaggerDateConverter;

namespace ESIClient.Dotcore.Model
{
    /// <summary>
    /// 200 ok object
    /// </summary>
    [DataContract]
    public partial class GetMarketsPrices200Ok :  IEquatable<GetMarketsPrices200Ok>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetMarketsPrices200Ok" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetMarketsPrices200Ok() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetMarketsPrices200Ok" /> class.
        /// </summary>
        /// <param name="adjustedPrice">adjusted_price number.</param>
        /// <param name="averagePrice">average_price number.</param>
        /// <param name="typeId">type_id integer (required).</param>
        public GetMarketsPrices200Ok(double? adjustedPrice = default(double?), double? averagePrice = default(double?), int? typeId = default(int?))
        {
            // to ensure "typeId" is required (not null)
            if (typeId == null)
            {
                throw new InvalidDataException("typeId is a required property for GetMarketsPrices200Ok and cannot be null");
            }
            else
            {
                this.TypeId = typeId;
            }
            this.AdjustedPrice = adjustedPrice;
            this.AveragePrice = averagePrice;
        }
        
        /// <summary>
        /// adjusted_price number
        /// </summary>
        /// <value>adjusted_price number</value>
        [DataMember(Name="adjusted_price", EmitDefaultValue=false)]
        public double? AdjustedPrice { get; set; }

        /// <summary>
        /// average_price number
        /// </summary>
        /// <value>average_price number</value>
        [DataMember(Name="average_price", EmitDefaultValue=false)]
        public double? AveragePrice { get; set; }

        /// <summary>
        /// type_id integer
        /// </summary>
        /// <value>type_id integer</value>
        [DataMember(Name="type_id", EmitDefaultValue=false)]
        public int? TypeId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GetMarketsPrices200Ok {\n");
            sb.Append("  AdjustedPrice: ").Append(AdjustedPrice).Append("\n");
            sb.Append("  AveragePrice: ").Append(AveragePrice).Append("\n");
            sb.Append("  TypeId: ").Append(TypeId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GetMarketsPrices200Ok);
        }

        /// <summary>
        /// Returns true if GetMarketsPrices200Ok instances are equal
        /// </summary>
        /// <param name="input">Instance of GetMarketsPrices200Ok to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetMarketsPrices200Ok input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.AdjustedPrice == input.AdjustedPrice ||
                    (this.AdjustedPrice != null &&
                    this.AdjustedPrice.Equals(input.AdjustedPrice))
                ) && 
                (
                    this.AveragePrice == input.AveragePrice ||
                    (this.AveragePrice != null &&
                    this.AveragePrice.Equals(input.AveragePrice))
                ) && 
                (
                    this.TypeId == input.TypeId ||
                    (this.TypeId != null &&
                    this.TypeId.Equals(input.TypeId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.AdjustedPrice != null)
                    hashCode = hashCode * 59 + this.AdjustedPrice.GetHashCode();
                if (this.AveragePrice != null)
                    hashCode = hashCode * 59 + this.AveragePrice.GetHashCode();
                if (this.TypeId != null)
                    hashCode = hashCode * 59 + this.TypeId.GetHashCode();
                return hashCode;
            }
        }
    }

}
