/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.8.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = ESIClient.Dotcore.Client.SwaggerDateConverter;

namespace ESIClient.Dotcore.Model
{
    /// <summary>
    /// 200 ok object
    /// </summary>
    [DataContract]
    public partial class GetUniverseFactions200Ok :  IEquatable<GetUniverseFactions200Ok>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetUniverseFactions200Ok" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetUniverseFactions200Ok() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetUniverseFactions200Ok" /> class.
        /// </summary>
        /// <param name="corporationId">corporation_id integer.</param>
        /// <param name="description">description string (required).</param>
        /// <param name="factionId">faction_id integer (required).</param>
        /// <param name="isUnique">is_unique boolean (required).</param>
        /// <param name="militiaCorporationId">militia_corporation_id integer.</param>
        /// <param name="name">name string (required).</param>
        /// <param name="sizeFactor">size_factor number (required).</param>
        /// <param name="solarSystemId">solar_system_id integer.</param>
        /// <param name="stationCount">station_count integer (required).</param>
        /// <param name="stationSystemCount">station_system_count integer (required).</param>
        public GetUniverseFactions200Ok(int? corporationId = default(int?), string description = default(string), int? factionId = default(int?), bool? isUnique = default(bool?), int? militiaCorporationId = default(int?), string name = default(string), float? sizeFactor = default(float?), int? solarSystemId = default(int?), int? stationCount = default(int?), int? stationSystemCount = default(int?))
        {
            // to ensure "description" is required (not null)
            if (description == null)
            {
                throw new InvalidDataException("description is a required property for GetUniverseFactions200Ok and cannot be null");
            }
            else
            {
                this.Description = description;
            }
            // to ensure "factionId" is required (not null)
            if (factionId == null)
            {
                throw new InvalidDataException("factionId is a required property for GetUniverseFactions200Ok and cannot be null");
            }
            else
            {
                this.FactionId = factionId;
            }
            // to ensure "isUnique" is required (not null)
            if (isUnique == null)
            {
                throw new InvalidDataException("isUnique is a required property for GetUniverseFactions200Ok and cannot be null");
            }
            else
            {
                this.IsUnique = isUnique;
            }
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new InvalidDataException("name is a required property for GetUniverseFactions200Ok and cannot be null");
            }
            else
            {
                this.Name = name;
            }
            // to ensure "sizeFactor" is required (not null)
            if (sizeFactor == null)
            {
                throw new InvalidDataException("sizeFactor is a required property for GetUniverseFactions200Ok and cannot be null");
            }
            else
            {
                this.SizeFactor = sizeFactor;
            }
            // to ensure "stationCount" is required (not null)
            if (stationCount == null)
            {
                throw new InvalidDataException("stationCount is a required property for GetUniverseFactions200Ok and cannot be null");
            }
            else
            {
                this.StationCount = stationCount;
            }
            // to ensure "stationSystemCount" is required (not null)
            if (stationSystemCount == null)
            {
                throw new InvalidDataException("stationSystemCount is a required property for GetUniverseFactions200Ok and cannot be null");
            }
            else
            {
                this.StationSystemCount = stationSystemCount;
            }
            this.CorporationId = corporationId;
            this.MilitiaCorporationId = militiaCorporationId;
            this.SolarSystemId = solarSystemId;
        }
        
        /// <summary>
        /// corporation_id integer
        /// </summary>
        /// <value>corporation_id integer</value>
        [DataMember(Name="corporation_id", EmitDefaultValue=false)]
        public int? CorporationId { get; set; }

        /// <summary>
        /// description string
        /// </summary>
        /// <value>description string</value>
        [DataMember(Name="description", EmitDefaultValue=false)]
        public string Description { get; set; }

        /// <summary>
        /// faction_id integer
        /// </summary>
        /// <value>faction_id integer</value>
        [DataMember(Name="faction_id", EmitDefaultValue=false)]
        public int? FactionId { get; set; }

        /// <summary>
        /// is_unique boolean
        /// </summary>
        /// <value>is_unique boolean</value>
        [DataMember(Name="is_unique", EmitDefaultValue=false)]
        public bool? IsUnique { get; set; }

        /// <summary>
        /// militia_corporation_id integer
        /// </summary>
        /// <value>militia_corporation_id integer</value>
        [DataMember(Name="militia_corporation_id", EmitDefaultValue=false)]
        public int? MilitiaCorporationId { get; set; }

        /// <summary>
        /// name string
        /// </summary>
        /// <value>name string</value>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// size_factor number
        /// </summary>
        /// <value>size_factor number</value>
        [DataMember(Name="size_factor", EmitDefaultValue=false)]
        public float? SizeFactor { get; set; }

        /// <summary>
        /// solar_system_id integer
        /// </summary>
        /// <value>solar_system_id integer</value>
        [DataMember(Name="solar_system_id", EmitDefaultValue=false)]
        public int? SolarSystemId { get; set; }

        /// <summary>
        /// station_count integer
        /// </summary>
        /// <value>station_count integer</value>
        [DataMember(Name="station_count", EmitDefaultValue=false)]
        public int? StationCount { get; set; }

        /// <summary>
        /// station_system_count integer
        /// </summary>
        /// <value>station_system_count integer</value>
        [DataMember(Name="station_system_count", EmitDefaultValue=false)]
        public int? StationSystemCount { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GetUniverseFactions200Ok {\n");
            sb.Append("  CorporationId: ").Append(CorporationId).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  FactionId: ").Append(FactionId).Append("\n");
            sb.Append("  IsUnique: ").Append(IsUnique).Append("\n");
            sb.Append("  MilitiaCorporationId: ").Append(MilitiaCorporationId).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  SizeFactor: ").Append(SizeFactor).Append("\n");
            sb.Append("  SolarSystemId: ").Append(SolarSystemId).Append("\n");
            sb.Append("  StationCount: ").Append(StationCount).Append("\n");
            sb.Append("  StationSystemCount: ").Append(StationSystemCount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GetUniverseFactions200Ok);
        }

        /// <summary>
        /// Returns true if GetUniverseFactions200Ok instances are equal
        /// </summary>
        /// <param name="input">Instance of GetUniverseFactions200Ok to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetUniverseFactions200Ok input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.CorporationId == input.CorporationId ||
                    (this.CorporationId != null &&
                    this.CorporationId.Equals(input.CorporationId))
                ) && 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                ) && 
                (
                    this.FactionId == input.FactionId ||
                    (this.FactionId != null &&
                    this.FactionId.Equals(input.FactionId))
                ) && 
                (
                    this.IsUnique == input.IsUnique ||
                    (this.IsUnique != null &&
                    this.IsUnique.Equals(input.IsUnique))
                ) && 
                (
                    this.MilitiaCorporationId == input.MilitiaCorporationId ||
                    (this.MilitiaCorporationId != null &&
                    this.MilitiaCorporationId.Equals(input.MilitiaCorporationId))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.SizeFactor == input.SizeFactor ||
                    (this.SizeFactor != null &&
                    this.SizeFactor.Equals(input.SizeFactor))
                ) && 
                (
                    this.SolarSystemId == input.SolarSystemId ||
                    (this.SolarSystemId != null &&
                    this.SolarSystemId.Equals(input.SolarSystemId))
                ) && 
                (
                    this.StationCount == input.StationCount ||
                    (this.StationCount != null &&
                    this.StationCount.Equals(input.StationCount))
                ) && 
                (
                    this.StationSystemCount == input.StationSystemCount ||
                    (this.StationSystemCount != null &&
                    this.StationSystemCount.Equals(input.StationSystemCount))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CorporationId != null)
                    hashCode = hashCode * 59 + this.CorporationId.GetHashCode();
                if (this.Description != null)
                    hashCode = hashCode * 59 + this.Description.GetHashCode();
                if (this.FactionId != null)
                    hashCode = hashCode * 59 + this.FactionId.GetHashCode();
                if (this.IsUnique != null)
                    hashCode = hashCode * 59 + this.IsUnique.GetHashCode();
                if (this.MilitiaCorporationId != null)
                    hashCode = hashCode * 59 + this.MilitiaCorporationId.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.SizeFactor != null)
                    hashCode = hashCode * 59 + this.SizeFactor.GetHashCode();
                if (this.SolarSystemId != null)
                    hashCode = hashCode * 59 + this.SolarSystemId.GetHashCode();
                if (this.StationCount != null)
                    hashCode = hashCode * 59 + this.StationCount.GetHashCode();
                if (this.StationSystemCount != null)
                    hashCode = hashCode * 59 + this.StationSystemCount.GetHashCode();
                return hashCode;
            }
        }
    }

}
