/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.7.5
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = ESIClient.Client.SwaggerDateConverter;

namespace ESIClient.Model
{
    /// <summary>
    /// destination object
    /// </summary>
    [DataContract]
    public partial class GetUniverseStargatesStargateIdDestination :  IEquatable<GetUniverseStargatesStargateIdDestination>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetUniverseStargatesStargateIdDestination" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetUniverseStargatesStargateIdDestination() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetUniverseStargatesStargateIdDestination" /> class.
        /// </summary>
        /// <param name="systemId">The solar system this stargate connects to (required).</param>
        /// <param name="stargateId">The stargate this stargate connects to (required).</param>
        public GetUniverseStargatesStargateIdDestination(int? systemId = default(int?), int? stargateId = default(int?))
        {
            // to ensure "systemId" is required (not null)
            if (systemId == null)
            {
                throw new InvalidDataException("systemId is a required property for GetUniverseStargatesStargateIdDestination and cannot be null");
            }
            else
            {
                this.SystemId = systemId;
            }
            // to ensure "stargateId" is required (not null)
            if (stargateId == null)
            {
                throw new InvalidDataException("stargateId is a required property for GetUniverseStargatesStargateIdDestination and cannot be null");
            }
            else
            {
                this.StargateId = stargateId;
            }
        }
        
        /// <summary>
        /// The solar system this stargate connects to
        /// </summary>
        /// <value>The solar system this stargate connects to</value>
        [DataMember(Name="system_id", EmitDefaultValue=false)]
        public int? SystemId { get; set; }

        /// <summary>
        /// The stargate this stargate connects to
        /// </summary>
        /// <value>The stargate this stargate connects to</value>
        [DataMember(Name="stargate_id", EmitDefaultValue=false)]
        public int? StargateId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GetUniverseStargatesStargateIdDestination {\n");
            sb.Append("  SystemId: ").Append(SystemId).Append("\n");
            sb.Append("  StargateId: ").Append(StargateId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GetUniverseStargatesStargateIdDestination);
        }

        /// <summary>
        /// Returns true if GetUniverseStargatesStargateIdDestination instances are equal
        /// </summary>
        /// <param name="input">Instance of GetUniverseStargatesStargateIdDestination to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetUniverseStargatesStargateIdDestination input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.SystemId == input.SystemId ||
                    (this.SystemId != null &&
                    this.SystemId.Equals(input.SystemId))
                ) && 
                (
                    this.StargateId == input.StargateId ||
                    (this.StargateId != null &&
                    this.StargateId.Equals(input.StargateId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.SystemId != null)
                    hashCode = hashCode * 59 + this.SystemId.GetHashCode();
                if (this.StargateId != null)
                    hashCode = hashCode * 59 + this.StargateId.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
